languageCode = "fr-fr"
title = "Pôle Kiné-Ostéo du Port"
theme = "hugo-hero-theme"
baseURL = "/"
#baseURL = "//davidcrte.github.io/projetpolekineosteo_v1/"
themesDir = "themes"
#test pour bug images déploiement

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"

#pour l'indexation
[sitemap]
  changeFreq = ''
  filename = 'sitemap.xml'
  priority = -1    
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "./images/logo-mobile.svg"
    #mobile_height = "36px"
    #mobile_width = "36px"
    desktop = "./accueil/logo2.png"
    #desktop_height = "29px"
    #desktop_width = "217px"
    alt = "Logo Pole Kiné Ostéo du Port"

  [params.homepage_meta_tags]
    meta_description = "Le Pôle Kiné Ostéo du Port vous accueille à Brest pour des séances de kinésithérapie et d'ostéopathie. Nous proposons de la thérapie manuelle, du dry needling, des ondes de choc, de l'analyse de course et la prise en charge du cancer du sein en kiné."
    meta_og_title = "Pôle Kiné Ostéo du Port Brest"
    meta_og_type = "website"
    meta_og_url = "https://hugo-hero.netlify.app"
    #meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Le Pôle Kiné Ostéo du Port vous accueille à Brest pour des séances de kinésithérapie et d'ostéopathie. Nous proposons de la thérapie manuelle, du dry needling, des ondes de choc, de l'analyse de course et la prise en charge du cancer du sein en kiné."
    #meta_twitter_card = "summary"
    #meta_twitter_site = "@zerostaticio"
    #meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "Accueil"
	url = "/"
  weight = 1

[[menu.main]]
	name = "Le cabinet"
	url = "/cabinet/"
  weight = 2

[[menu.main]]
  identifier = "equipe"
	name = "L'équipe"
	url = "/equipe/"
  weight = 3       

[[menu.main]]
  name = "Nous Contacter"
  url = "/contact/"
  weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
